baseUrl: http://tz.tmsf.com/newhouse/property_searchall.htm
httpConnectTimeout: 100000
httpReadTimeout:  100000
httpWriteTimeout:  100000
httpMethod:  GET
#httpHeader:
#httpPostParams:
#httpBody:
basePagingTaskNum: 1
basePageStart: 1
basePageEnd: -1 #less than 0 means end is tatal pages
basePageUrl: http://tz.tmsf.com/newhouse/property_searchall.htm
basePageInfoType: HTML_ELE_EXTRAT
basePageInfoPatternStr: (\\d+)页
basePageInfoSelector: "#AspNetPager1 > table > tbody > tr > td:nth-child(1)"
