baseUrl: "http://219.131.222.106:30090/LeadingGH/Include/Execute/WWGS.ashx?userName=gszh&gridKey=8f735360-c975-4683-8bfc-e0929086694e"
httpConnectTimeout: 100000
httpReadTimeout:  100000
httpWriteTimeout:  100000
httpMethod:  POST
#httpHeader:
#httpPostParams:
httpBody: "<PDoc Tag='GetYSPrjInfo' />"
basePagingTaskNum: 1
basePageStart: 1
basePageEnd: -1 #less than 0 means end is tatal pages
basePageUrl: "http://219.131.222.106:30090/leadinggh/include/wwgs.html?userName=gszh&gridKey=8f735360-c975-4683-8bfc-e0929086694e"
basePageInfoType: HTML_ELE_EXTRAT
basePageInfoPatternStr: (\\d+)页
basePageInfoSelector: "#AspNetPager1 > table > tbody > tr > td:nth-child(1)"